version: "3"
services:
  # START PIHOLE
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    volumes:
      - "${VOLUMES_PATH}/pihole/etc-pihole/:/etc/pihole/"
      - "${VOLUMES_PATH}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      VIRTUAL_HOST: pihole.${TLD}
      LETSENCRYPT_HOST: pihole.${TLD}
      VIRTUAL_PORT: 80
      TZ: Europe/Zurich
    restart: unless-stopped
    networks:
      - base-network
  # END PIHOLE
  # START NETDATA
  netdata:
    image: netdata/netdata:latest
    hostname: netdata.${TLD}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker-proxy-acl/docker.sock:/var/run/docker.sock:ro
    environment:
      VIRTUAL_HOST: netdata.${TLD}
      LETSENCRYPT_HOST: netdata.${TLD}
      VIRTUAL_PORT: 19999
    restart: unless-stopped
    depends_on:
      - docker-proxy
    networks:
      - base-network
  # END NETDATA
  # START PORTAINER
  portainer:
    image: portainer/portainer:latest
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${VOLUMES_PATH}/portainer:/data'
    environment:
      VIRTUAL_HOST: portainer.${TLD}
      LETSENCRYPT_HOST: portainer.${TLD}
      VIRTUAL_PORT: 9000
    networks:
      - base-network
    restart: unless-stopped
  # END PORTAINER
  # START DOCKER PROXY
  docker-proxy:
    image: qmcgaw/docker-proxy-acl-alpine:latest
    volumes:
      - /var/run/docker-proxy-acl:/tmp/docker-proxy-acl
      - /var/run/docker.sock:/var/run/docker.sock
    command: -a containers
    network_mode: none
    restart: always
  # END DOCKER PROXY
  # START Public IP Monitor
  public-ip-monitor:
    image: muyajil/public-ip-slack-notifier:latest
    environment:
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    restart: unless-stopped
  # END Public IP Monitor

networks:
  base-network:
    external: true
